# For development use only

web:
  build: .
  dockerfile: development.Dockerfile
  environment:
    - NODE_ENV=development
  links:
    - db
  ports:
    - "1337:1337"
  volumes:
    - .:/usr/src/app
  working_dir: /usr/src/app
db:
  image: mongo
  ports:
    - "27017:27017"
